OD_PROJECT_ID = ''
OD_ITERATION_ID = ''
OD_ITERATION_NAME = ''
OD_PREDICTION_KEY = ''

CLASSIFIER_PROJECT_ID = ''
CLASSIFIER_ITERATION_NAME = ''
CLASSIFIER_PREDICTION_KEY = ''

ENDPOINT = ''
IMAGES_FOLDER = '../guessed-images/'
MIN_IMG_WIDTH = 100
MIN_IMG_HEIGHT = 100
